---
- name: Disable and stop automatic apt updates
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - unattended-upgrades.service
    - apt-daily.timer
    - apt-daily-upgrade.timer

- name: Disable APT auto-update configs
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "0";
      APT::Periodic::Unattended-Upgrade "0";
    mode: "0644"
