---
- name: Add Argo repository
  kubernetes.core.helm_repository:
    name: argo
    repo_url: "{{ configure_k8s_argo_repo_url }}"

- name: Ensure directory for Helm values files exists
  ansible.builtin.file:
    path: "/home/ubuntu/helm/argo"
    state: directory
    mode: "0755"
    owner: ubuntu
    group: ubuntu

- name: Template Argo values
  ansible.builtin.template:
    src: argo-values.yaml.j2
    dest: "/home/ubuntu/helm/argo/argo-values.yaml"
    mode: "0644"
    owner: ubuntu
    group: ubuntu

- name: Install Argo via Helm
  kubernetes.core.helm:
    state: present
    name: argo
    chart_ref: argo/argo
    chart_version: "{{ configure_k8s_argo_version }}"
    namespace: kube-system
    wait: true
    wait_timeout: "10m0s"
    kubeconfig: "/etc/kubernetes/admin.conf"
    update_repo_cache: true
    history_max: 3
    atomic: false
    values_files: "/home/ubuntu/helm/argo/argo-values.yaml"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
