---
- name: Initialize master
  ansible.builtin.include_tasks: init_master.yml
  when: inventory_hostname == groups['masters'][0]

- name: Join masters
  ansible.builtin.include_tasks: join_masters.yml
  when: inventory_hostname in groups['masters'] | difference([groups['masters'][0]])

- name: Join workers
  ansible.builtin.include_tasks: join_workers.yml
  when: inventory_hostname in groups['workers']

- name: Install Helm
  ansible.builtin.include_tasks: helm_install.yml
  when: inventory_hostname in groups['masters']

- name: Install Cilium
  ansible.builtin.include_tasks: cilium_install.yml
  when: inventory_hostname in groups['masters'][0]

- name: Install Argo CD
  ansible.builtin.include_tasks: argocd_install.yml
  when: inventory_hostname in groups['masters'][0]
